'use strict';
// OmniHub CRM client module v1.9.0.
(function(){
  const HIGH=['administrator','manager','auditor'], WRITE=['administrator','manager'];
  const STAGES=['new','contacted','qualified','proposal','negotiation','nurture','won','lost'];
  const S={customers:[],leads:[],campaigns:[],dashboard:null,cash:null,customer:null,channel:null};
  const $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money=(v,c='USD')=>`${c} ${Number(v||0).toFixed(2)}`, date=v=>v?new Date(v).toLocaleString():'—';
  const today=n=>{const d=new Date();d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)};
  const ctx=()=>{const c=window.OmniHubCRMContext;if(!c)return null;return {db:typeof c.supabase==='function'?c.supabase():c.supabase,profile:typeof c.getProfile==='function'?c.getProfile():c.profile}};
  const canWrite=()=>WRITE.includes(ctx()?.profile?.role);
  const client=()=>{const c=ctx()?.db;if(!c)throw new Error('The secure database session is not ready.');return c};
  const status=(id,msg,bad=false)=>{const e=$(id);if(e){e.textContent=msg;e.className=`crm-status ${bad?'error':'ok'}`}};
  const rpc=async(name,args)=>{const {data,error}=await client().rpc(name,args);if(error)throw error;return data};
  const tags=v=>String(v||'').split(',').map(x=>x.trim()).filter(Boolean);
  const obj=form=>Object.fromEntries(new FormData(form).entries());
  function csv(name,headers,rows){const q=v=>`"${String(v??'').replaceAll('"','""')}"`,blob=new Blob([[headers,...rows].map(r=>r.map(q).join(',')).join('\n')],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href)}
  const STYLE=`
  .crm-page{display:none}.crm-page.crm-active{display:block}.crm-shell{display:grid;gap:14px;color:inherit}
  .crm-hero{display:flex;justify-content:space-between;align-items:flex-start;gap:16px;padding:18px;border:1px solid rgba(128,128,128,.25);border-left:4px solid #ef1721;border-radius:16px;background:linear-gradient(135deg,rgba(239,23,33,.12),rgba(118,68,255,.08))}
  .crm-hero h2{margin:0 0 5px;font-size:22px}.crm-hero p{margin:0;opacity:.75;max-width:760px}.crm-toolbar,.crm-actions{display:flex;flex-wrap:wrap;align-items:center;gap:8px}
  .crm-grid{display:grid;grid-template-columns:repeat(12,minmax(0,1fr));gap:12px}.crm-card{grid-column:span 3;padding:15px;border:1px solid rgba(128,128,128,.25);border-radius:14px;background:rgba(128,128,128,.07)}
  .crm-card .label{font-size:10px;text-transform:uppercase;letter-spacing:.08em;opacity:.7}.crm-card strong{display:block;margin:5px 0;font-size:20px}.crm-panel{padding:16px;border:1px solid rgba(128,128,128,.25);border-radius:14px;background:rgba(128,128,128,.04)}
  .crm-panel h3{margin:0 0 12px}.crm-two{display:grid;grid-template-columns:minmax(0,1.4fr) minmax(320px,.8fr);gap:14px}.crm-form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.crm-wide{grid-column:1/-1}
  .crm-field{display:grid;gap:5px}.crm-field label{font-size:11px;font-weight:700;opacity:.72}.crm-field input,.crm-field select,.crm-field textarea,.crm-toolbar input,.crm-toolbar select{width:100%;min-height:38px;padding:8px 10px;border:1px solid rgba(128,128,128,.35);border-radius:9px;background:var(--card,#fff);color:inherit}
  .crm-field textarea{min-height:72px;resize:vertical}.crm-check{display:flex;align-items:center;gap:8px}.crm-check input{width:auto;min-height:auto}.crm-button{min-height:35px;padding:8px 11px;border:0;border-radius:9px;background:#ef1721;color:#fff;font-weight:750;cursor:pointer}
  .crm-button.secondary{background:#262626}.crm-button.ghost{border:1px solid rgba(128,128,128,.35);background:transparent;color:inherit}.crm-button.danger{background:#9f1420}.crm-write-hidden{display:none!important}
  .crm-table-wrap{overflow:auto;max-height:520px}.crm-table{width:100%;border-collapse:collapse;font-size:12px}.crm-table th{position:sticky;top:0;z-index:1;background:var(--card,#fff);text-align:left;font-size:10px;text-transform:uppercase;letter-spacing:.05em}.crm-table th,.crm-table td{padding:9px 7px;border-bottom:1px solid rgba(128,128,128,.2);vertical-align:top}
  .crm-pill{display:inline-flex;padding:3px 7px;border-radius:999px;background:rgba(118,68,255,.14);font-size:10px;font-weight:800;text-transform:uppercase}.crm-pill.won,.crm-pill.active,.crm-pill.completed{background:rgba(31,171,92,.15);color:#128445}.crm-pill.lost,.crm-pill.archived{background:rgba(220,53,69,.15);color:#b62432}
  .crm-status{min-height:18px;margin-top:7px;font-size:12px;font-weight:700}.crm-status.ok{color:#168948}.crm-status.error{color:#d52334}.crm-empty{padding:24px;text-align:center;opacity:.68}.crm-list{display:grid;gap:7px}.crm-item{padding:9px;border:1px solid rgba(128,128,128,.2);border-radius:9px}.crm-muted{opacity:.7;font-size:11px}
  .crm-chart{display:grid;gap:7px}.crm-bar{display:grid;grid-template-columns:100px minmax(60px,1fr) 55px;gap:7px;align-items:center}.crm-track{height:9px;border-radius:99px;background:rgba(128,128,128,.18);overflow:hidden}.crm-fill{display:block;height:100%;background:linear-gradient(90deg,#ef1721,#7644ff)}
  @media(max-width:900px){.crm-card{grid-column:span 6}.crm-two{grid-template-columns:1fr}.crm-form{grid-template-columns:1fr}.crm-wide{grid-column:auto}}@media(max-width:560px){.crm-card{grid-column:1/-1}.crm-panel{padding:12px}.crm-hero{flex-direction:column}}
  `;
  const customerHTML=()=>`<section id="crmCustomersWorkspace" class="crm-page"><div class="crm-shell">
    <div class="crm-hero"><div><h2>Customers &amp; CRM</h2><p>Customer master records, contacts, consent, balances, follow-ups, segmentation and complete 360-degree history.</p></div><div class="crm-actions"><button class="crm-button crm-write" id="crmNewCustomer">New customer</button><button class="crm-button secondary" id="crmExportCustomers">Export CSV</button></div></div>
    <div class="crm-grid"><div class="crm-card"><span class="label">Active customers</span><strong id="crmCustomerCount">0</strong></div><div class="crm-card"><span class="label">Follow-ups due</span><strong id="crmFollowupCount">0</strong></div><div class="crm-card"><span class="label">At risk / dormant</span><strong id="crmRiskCount">0</strong></div><div class="crm-card"><span class="label">Marketing consent</span><strong id="crmConsentCount">0</strong></div></div>
    <div class="crm-toolbar"><input id="crmCustomerSearch" placeholder="Search customer, phone, email, code or tag"><select id="crmCustomerStage"><option value="">All lifecycle stages</option><option>prospect</option><option>active</option><option>at_risk</option><option>dormant</option><option>vip</option><option>archived</option></select><select id="crmCustomerSegment"><option value="">All segments</option><option>standard</option><option>vip</option><option>wholesale</option><option>corporate</option><option>government</option><option>school</option><option>church</option></select><button class="crm-button ghost" id="crmRefreshCustomers">Refresh</button></div>
    <div class="crm-two"><div class="crm-panel"><h3>Customer directory</h3><div class="crm-table-wrap"><table class="crm-table"><thead><tr><th>Customer</th><th>Contact</th><th>Segment</th><th>Lifecycle</th><th>Follow-up</th><th>Actions</th></tr></thead><tbody id="crmCustomerRows"></tbody></table></div><div id="crmCustomerStatus" class="crm-status"></div></div>
    <div class="crm-panel" id="crmCustomerEditor"><h3 id="crmCustomerFormTitle">Customer profile</h3><form id="crmCustomerForm" class="crm-form">
      <input type="hidden" name="id"><div class="crm-field"><label>Customer name *</label><input name="name" required></div><div class="crm-field"><label>Type</label><select name="customer_type"><option>individual</option><option>business</option><option>government</option><option>nonprofit</option><option>school</option><option>church</option><option>other</option></select></div>
      <div class="crm-field"><label>Company</label><input name="company_name"></div><div class="crm-field"><label>Contact person</label><input name="contact_person"></div><div class="crm-field"><label>Phone</label><input name="phone"></div><div class="crm-field"><label>Secondary phone</label><input name="secondary_phone"></div>
      <div class="crm-field"><label>Email</label><input name="email" type="email"></div><div class="crm-field"><label>Website</label><input name="website"></div><div class="crm-field crm-wide"><label>Address</label><input name="address"></div><div class="crm-field"><label>City</label><input name="city"></div><div class="crm-field"><label>Country</label><input name="country" value="Zimbabwe"></div>
      <div class="crm-field"><label>Segment</label><input name="segment" value="standard"></div><div class="crm-field"><label>Lifecycle</label><select name="lifecycle_stage"><option>prospect</option><option selected>active</option><option>at_risk</option><option>dormant</option><option>vip</option></select></div>
      <div class="crm-field"><label>Acquisition source</label><input name="acquisition_source"></div><div class="crm-field"><label>Preferred channel</label><select name="preferred_channel"><option>whatsapp</option><option>phone</option><option>email</option><option>sms</option><option>in_person</option><option>none</option></select></div>
      <div class="crm-field"><label>Tax ID</label><input name="tax_id"></div><div class="crm-field"><label>Credit limit</label><input name="credit_limit" type="number" min="0" step=".01" value="0"></div><div class="crm-field"><label>Opening balance</label><input name="opening_balance" type="number" step=".01" value="0"></div><div class="crm-field"><label>Next follow-up</label><input name="next_followup_at" type="datetime-local"></div>
      <div class="crm-field crm-wide"><label>Tags (comma separated)</label><input name="tags"></div><div class="crm-field crm-wide"><label>Notes</label><textarea name="notes"></textarea></div><label class="crm-check"><input name="marketing_consent" type="checkbox"> Marketing consent</label><label class="crm-check"><input name="do_not_contact" type="checkbox"> Do not contact</label>
      <div class="crm-wide crm-actions"><button class="crm-button crm-write" type="submit">Save customer</button><button class="crm-button ghost" type="button" id="crmCancelCustomer">Clear</button></div>
    </form><div id="crmCustomerFormStatus" class="crm-status"></div></div></div>
    <div class="crm-panel"><h3>Customer 360</h3><div id="crmCustomer360" class="crm-empty">Select “360 view” to inspect contacts, activities, linked sales, jobs, documents, communications and outstanding balances.</div></div>
  </div></section>`;
  const leadHTML=()=>`<section id="crmLeadsWorkspace" class="crm-page"><div class="crm-shell">
    <div class="crm-hero"><div><h2>Leads &amp; Conversions</h2><p>Capture, assign, nurture and convert opportunities with stage history, activities, campaign attribution, forecasts and source analytics.</p></div><div class="crm-actions"><button class="crm-button crm-write" id="crmNewLead">New lead</button><button class="crm-button secondary" id="crmExportLeads">Export CSV</button></div></div>
    <div class="crm-toolbar"><label>From <input id="crmDashFrom" type="date"></label><label>To <input id="crmDashTo" type="date"></label><select id="crmLeadStageFilter"><option value="">All stages</option>${STAGES.map(x=>`<option>${x}</option>`).join('')}</select><input id="crmLeadSearch" placeholder="Search lead, company, source or code"><button class="crm-button ghost" id="crmRefreshLeads">Refresh</button></div>
    <div class="crm-grid"><div class="crm-card"><span class="label">Open leads</span><strong id="crmOpenLeads">0</strong></div><div class="crm-card"><span class="label">Won</span><strong id="crmWonLeads">0</strong></div><div class="crm-card"><span class="label">Conversion rate</span><strong id="crmConversionRate">0%</strong></div><div class="crm-card"><span class="label">Weighted pipeline</span><strong id="crmWeightedValue">USD 0.00</strong></div></div>
    <div class="crm-grid"><div class="crm-panel" style="grid-column:span 7"><h3>Pipeline funnel</h3><div id="crmFunnel" class="crm-chart"></div></div><div class="crm-panel" style="grid-column:span 5"><h3>Lead sources</h3><div id="crmSources" class="crm-chart"></div></div></div>
    <div class="crm-two"><div class="crm-panel"><h3>Pipeline</h3><div class="crm-table-wrap"><table class="crm-table"><thead><tr><th>Lead</th><th>Stage</th><th>Value</th><th>Probability</th><th>Follow-up</th><th>Actions</th></tr></thead><tbody id="crmLeadRows"></tbody></table></div><div id="crmLeadStatus" class="crm-status"></div></div>
    <div class="crm-panel"><h3 id="crmLeadFormTitle">Lead record</h3><form id="crmLeadForm" class="crm-form">
      <input type="hidden" name="id"><div class="crm-field"><label>Name *</label><input name="name" required></div><div class="crm-field"><label>Company</label><input name="company_name"></div><div class="crm-field"><label>Phone</label><input name="phone"></div><div class="crm-field"><label>Email</label><input name="email" type="email"></div>
      <div class="crm-field"><label>Source</label><input name="source" value="walk_in"></div><div class="crm-field"><label>Campaign</label><select name="campaign_id" id="crmLeadCampaign"><option value="">No campaign</option></select></div><div class="crm-field"><label>Stage</label><select name="stage">${STAGES.slice(0,6).map(x=>`<option>${x}</option>`).join('')}</select></div><div class="crm-field"><label>Currency</label><select name="currency"><option>USD</option><option>ZiG</option></select></div>
      <div class="crm-field"><label>Estimated value</label><input name="estimated_value" type="number" min="0" step=".01" value="0"></div><div class="crm-field"><label>Probability %</label><input name="probability" type="number" min="0" max="100" value="10"></div><div class="crm-field"><label>Expected close</label><input name="expected_close_date" type="date"></div><div class="crm-field"><label>Next follow-up</label><input name="next_followup_at" type="datetime-local"></div>
      <div class="crm-field crm-wide"><label>Requirements</label><textarea name="requirements"></textarea></div><div class="crm-field crm-wide"><label>Notes</label><textarea name="notes"></textarea></div><div class="crm-field crm-wide"><label>Tags</label><input name="tags"></div><div class="crm-wide crm-actions"><button class="crm-button crm-write" type="submit">Save lead</button><button class="crm-button ghost" type="button" id="crmCancelLead">Clear</button></div>
    </form><div id="crmLeadFormStatus" class="crm-status"></div></div></div>
    <div class="crm-two"><div class="crm-panel"><h3>Activities &amp; follow-ups</h3><form id="crmActivityForm" class="crm-form">
      <div class="crm-field"><label>Customer</label><select name="customer_id" id="crmActivityCustomer"><option value="">None</option></select></div><div class="crm-field"><label>Lead</label><select name="lead_id" id="crmActivityLead"><option value="">None</option></select></div>
      <div class="crm-field"><label>Type</label><select name="activity_type"><option>call</option><option>email</option><option>sms</option><option>whatsapp</option><option>meeting</option><option>visit</option><option>task</option><option>quotation</option><option>complaint</option><option>support</option><option>note</option><option>other</option></select></div><div class="crm-field"><label>Direction</label><select name="direction"><option>outbound</option><option>inbound</option><option>internal</option></select></div>
      <div class="crm-field crm-wide"><label>Subject *</label><input name="subject" required></div><div class="crm-field"><label>Schedule</label><input name="scheduled_at" type="datetime-local"></div><div class="crm-field"><label>Status</label><select name="status"><option>planned</option><option>completed</option></select></div><div class="crm-field crm-wide"><label>Details / outcome</label><textarea name="details"></textarea></div><div class="crm-wide"><button class="crm-button crm-write" type="submit">Log activity</button></div>
    </form><div id="crmActivityStatus" class="crm-status"></div><div id="crmUpcomingActivities" class="crm-list"></div></div>
    <div class="crm-panel"><h3>Campaigns</h3><form id="crmCampaignForm" class="crm-form"><div class="crm-field"><label>Name *</label><input name="name" required></div><div class="crm-field"><label>Channel</label><select name="channel"><option>mixed</option><option>whatsapp</option><option>social</option><option>referral</option><option>print</option><option>event</option><option>email</option><option>sms</option><option>other</option></select></div><div class="crm-field"><label>Budget</label><input name="budget" type="number" min="0" step=".01" value="0"></div><div class="crm-field"><label>Currency</label><select name="currency"><option>USD</option><option>ZiG</option></select></div><div class="crm-field"><label>Starts</label><input name="starts_on" type="date"></div><div class="crm-field"><label>Ends</label><input name="ends_on" type="date"></div><div class="crm-field crm-wide"><label>Objective</label><input name="objective"></div><div class="crm-wide"><button class="crm-button crm-write" type="submit">Create campaign</button></div></form><div id="crmCampaignStatus" class="crm-status"></div><div id="crmCampaignList" class="crm-list"></div></div></div>
  </div></section>`;
  const cashHTML=()=>`<section id="crmCashWorkspace" class="crm-page"><div class="crm-shell">
    <div class="crm-hero"><div><h2>Cash Conversion Cycle</h2><p>Recognised CCC plus actual operating-cash pressure from inventory purchasing and every recorded non-void operating expense.</p></div><button class="crm-button secondary" id="crmExportCash">Export breakdown</button></div>
    <div class="crm-toolbar"><label>From <input id="crmCashFrom" type="date"></label><label>To <input id="crmCashTo" type="date"></label><select id="crmCashCurrency"><option value="">USD and ZiG</option><option>USD</option><option>ZiG</option></select><button class="crm-button" id="crmRunCash">Run analysis</button></div>
    <div id="crmCashMethod" class="crm-panel crm-muted">Standard CCC = inventory days + receivable days − payable days. The operating view adds every expense and paid purchasing document.</div><div id="crmCashCards" class="crm-grid"></div>
    <div class="crm-two"><div class="crm-panel"><h3>Expense breakdown</h3><div class="crm-table-wrap"><table class="crm-table"><thead><tr><th>Currency</th><th>Category</th><th>Amount</th><th>Entries</th></tr></thead><tbody id="crmExpenseBreakdown"></tbody></table></div></div><div class="crm-panel"><h3>Purchasing drill-down</h3><div class="crm-table-wrap"><table class="crm-table"><thead><tr><th>Document</th><th>Type</th><th>Status</th><th>Total</th><th>Paid</th><th>Date</th></tr></thead><tbody id="crmPurchaseBreakdown"></tbody></table></div></div></div><div id="crmCashStatus" class="crm-status"></div>
  </div></section>`;
  function mount(){
    if($('crmCustomersWorkspace'))return;
    const style=document.createElement('style');style.textContent=STYLE;document.head.appendChild(style);
    const host=document.querySelector('main.content')||document.querySelector('.main');if(!host)throw new Error('OmniHub content host was not found.');
    host.insertAdjacentHTML('beforeend',customerHTML()+leadHTML()+cashHTML());nav();bind();role();
  }
  function nav(){
    const bottom=document.querySelector('.bottom-nav'), items=[['crmCustomersWorkspace','♙','CRM'],['crmLeadsWorkspace','↗','Leads'],['crmCashWorkspace','◈','Cash Cycle']];
    if(bottom)items.forEach(([view,icon,label])=>{const b=document.createElement('button');b.className='nav-btn crm-role-nav';b.dataset.crmView=view;b.innerHTML=`<span>${icon}</span><span>${label}</span>`;b.onclick=()=>open(view,b);bottom.appendChild(b)});
    else{const n=document.querySelector('.nav'),logout=n?.querySelector('#logoutBtn');items.forEach(([view,,label])=>{const b=document.createElement('button');b.className='crm-role-nav';b.dataset.crmView=view;b.textContent=label==='CRM'?'Customers & CRM':label==='Leads'?'Leads & Conversions':'Cash Conversion Cycle';b.onclick=()=>open(view,b);n?.insertBefore(b,logout||null)})}
  }
  function role(){const r=ctx()?.profile?.role;document.querySelectorAll('.crm-role-nav').forEach(x=>x.classList.toggle('hidden',!HIGH.includes(r)));document.querySelectorAll('.crm-write').forEach(x=>x.classList.toggle('crm-write-hidden',!WRITE.includes(r)))}
  function open(view,button){
    if(!HIGH.includes(ctx()?.profile?.role))return;
    document.querySelectorAll('.crm-page').forEach(x=>x.classList.remove('crm-active'));
    if(document.querySelector('main.content'))document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));else document.querySelectorAll('.main>section').forEach(x=>x.classList.add('hidden'));
    $(view).classList.remove('hidden');$(view).classList.add('crm-active');document.querySelectorAll('.nav-btn,.nav button').forEach(x=>x.classList.remove('active'));button?.classList.add('active');
    if(view==='crmCustomersWorkspace')loadCustomers();if(view==='crmLeadsWorkspace')loadCRM();if(view==='crmCashWorkspace')loadCash();(document.querySelector('.content')||document.querySelector('.main'))?.scrollTo({top:0});
  }
  function bind(){
    $('crmDashFrom').value=today(-30);$('crmDashTo').value=today(0);$('crmCashFrom').value=today(-30);$('crmCashTo').value=today(0);
    $('crmRefreshCustomers').onclick=loadCustomers;$('crmCustomerSearch').oninput=renderCustomers;$('crmCustomerStage').onchange=renderCustomers;$('crmCustomerSegment').onchange=renderCustomers;$('crmNewCustomer').onclick=resetCustomer;$('crmCancelCustomer').onclick=resetCustomer;$('crmCustomerForm').onsubmit=saveCustomer;
    $('crmExportCustomers').onclick=()=>csv(`OmniHub-Customers-${today(0)}.csv`,['Code','Name','Company','Phone','Email','Segment','Lifecycle','Follow-up','Tags'],S.customers.map(x=>[x.customer_code,x.name,x.company_name,x.phone,x.email,x.segment,x.lifecycle_stage,x.next_followup_at,(x.tags||[]).join('|')]));
    $('crmRefreshLeads').onclick=loadCRM;$('crmLeadSearch').oninput=renderLeads;$('crmLeadStageFilter').onchange=renderLeads;$('crmDashFrom').onchange=loadDashboard;$('crmDashTo').onchange=loadDashboard;$('crmNewLead').onclick=resetLead;$('crmCancelLead').onclick=resetLead;$('crmLeadForm').onsubmit=saveLead;$('crmActivityForm').onsubmit=saveActivity;$('crmCampaignForm').onsubmit=saveCampaign;
    $('crmExportLeads').onclick=()=>csv(`OmniHub-Leads-${today(0)}.csv`,['Code','Name','Company','Source','Stage','Currency','Value','Probability','Expected close','Follow-up'],S.leads.map(x=>[x.lead_code,x.name,x.company_name,x.source,x.stage,x.currency,x.estimated_value,x.probability,x.expected_close_date,x.next_followup_at]));
    $('crmRunCash').onclick=loadCash;$('crmExportCash').onclick=exportCash;
  }
  async function loadCustomers(){
    try{status('crmCustomerStatus','Loading customers…');const {data,error}=await client().from('customers').select('id,customer_code,name,customer_type,company_name,contact_person,phone,secondary_phone,email,address,website,city,country,preferred_channel,segment,lifecycle_stage,acquisition_source,tags,marketing_consent,do_not_contact,last_contact_at,next_followup_at,archived_at,archive_reason,tax_id,credit_limit,opening_balance,notes,created_at,updated_at').order('updated_at',{ascending:false}).limit(1000);if(error)throw error;S.customers=data||[];renderCustomers();relations();status('crmCustomerStatus',`${S.customers.length} customer record(s) loaded.`)}catch(e){status('crmCustomerStatus',e.message,true)}
  }
  function customerRows(){const q=$('crmCustomerSearch').value.toLowerCase(),stage=$('crmCustomerStage').value,segment=$('crmCustomerSegment').value;return S.customers.filter(x=>(!stage||x.lifecycle_stage===stage)&&(!segment||x.segment===segment)&&(!q||[x.customer_code,x.name,x.company_name,x.phone,x.email,...(x.tags||[])].some(v=>String(v||'').toLowerCase().includes(q))))}
  function renderCustomers(){
    const rows=customerRows(),body=$('crmCustomerRows');body.innerHTML=rows.length?'':'<tr><td colspan="6" class="crm-empty">No matching customers.</td></tr>';
    rows.forEach(x=>{const tr=document.createElement('tr');tr.innerHTML=`<td><strong>${esc(x.name)}</strong><div class="crm-muted">${esc(x.customer_code||x.company_name||'')}</div></td><td>${esc(x.phone||'—')}<div class="crm-muted">${esc(x.email||'')}</div></td><td>${esc(x.segment||'standard')}</td><td><span class="crm-pill ${esc(x.lifecycle_stage)}">${esc(x.lifecycle_stage)}</span></td><td>${date(x.next_followup_at)}</td><td class="crm-actions"></td>`;const a=tr.lastElementChild;[['360 view','ghost',()=>customer360(x)],['Edit','secondary',()=>editCustomer(x)],['Archive','danger',()=>archiveCustomer(x)]].forEach(([l,k,f],i)=>{const b=document.createElement('button');b.className=`crm-button ${k}`;b.textContent=l;b.onclick=f;if(i&& !canWrite())b.style.display='none';a.appendChild(b)});body.appendChild(tr)});
    $('crmCustomerCount').textContent=S.customers.filter(x=>!x.archived_at).length;$('crmFollowupCount').textContent=S.customers.filter(x=>x.next_followup_at&&new Date(x.next_followup_at)<=new Date()).length;$('crmRiskCount').textContent=S.customers.filter(x=>['at_risk','dormant'].includes(x.lifecycle_stage)).length;$('crmConsentCount').textContent=S.customers.filter(x=>x.marketing_consent&&!x.do_not_contact).length;
  }
  function resetCustomer(){const f=$('crmCustomerForm');f.reset();f.elements.id.value='';f.elements.country.value='Zimbabwe';f.elements.segment.value='standard';f.elements.lifecycle_stage.value='active';f.elements.preferred_channel.value='whatsapp';f.elements.credit_limit.value='0';f.elements.opening_balance.value='0';$('crmCustomerFormTitle').textContent='Customer profile';status('crmCustomerFormStatus','')}
  function editCustomer(x){if(!canWrite())return;resetCustomer();const f=$('crmCustomerForm');Object.entries(x).forEach(([k,v])=>{const i=f.elements[k];if(!i)return;if(i.type==='checkbox')i.checked=!!v;else if(i.type==='datetime-local')i.value=v?String(v).slice(0,16):'';else i.value=Array.isArray(v)?v.join(', '):(v??'')});$('crmCustomerFormTitle').textContent=`Edit ${x.customer_code||x.name}`;f.scrollIntoView({behavior:'smooth'})}
  async function saveCustomer(e){e.preventDefault();if(!canWrite())return status('crmCustomerFormStatus','Auditor access is read-only.',true);try{const raw=obj(e.currentTarget),id=raw.id||null;delete raw.id;raw.tags=tags(raw.tags);raw.marketing_consent=e.currentTarget.elements.marketing_consent.checked;raw.do_not_contact=e.currentTarget.elements.do_not_contact.checked;raw.credit_limit=Number(raw.credit_limit||0);raw.opening_balance=Number(raw.opening_balance||0);raw.next_followup_at=raw.next_followup_at?new Date(raw.next_followup_at).toISOString():null;await rpc('save_crm_customer',{p_customer_id:id,p_data:raw});resetCustomer();await loadCustomers();status('crmCustomerFormStatus',id?'Customer updated and audited.':'Customer created and audited.')}catch(x){status('crmCustomerFormStatus',x.message,true)}}
  async function archiveCustomer(x){if(!canWrite())return;const reason=prompt(`Reason for archiving ${x.name}`);if(reason===null)return;if(reason.trim().length<5)return alert('Enter at least 5 characters.');try{await rpc('archive_crm_customer',{p_customer_id:x.id,p_reason:reason.trim()});await loadCustomers()}catch(e){status('crmCustomerStatus',e.message,true)}}
  async function customer360(x){
    const p=$('crmCustomer360');p.innerHTML='<div class="crm-empty">Loading Customer 360…</div>';
    try{const d=await rpc('get_customer_360',{p_customer_id:x.id});S.customer=x;const m=d.metrics||{},map=o=>Object.entries(o||{}).map(([c,v])=>money(v,c)).join(' · ')||'—',list=(a,r)=>a?.length?`<div class="crm-list">${a.map(r).join('')}</div>`:'<div class="crm-empty">No records.</div>';
      p.innerHTML=`<div class="crm-grid"><div class="crm-card"><span class="label">Sales</span><strong>${m.sales_count||0}</strong><div>${esc(map(m.sales_value))}</div></div><div class="crm-card"><span class="label">Jobs</span><strong>${m.jobs||0}</strong><div>${m.open_jobs||0} open</div></div><div class="crm-card"><span class="label">Documents</span><strong>${m.documents||0}</strong></div><div class="crm-card"><span class="label">Outstanding</span><strong>${esc(map(m.outstanding))}</strong></div></div><div class="crm-actions crm-write"><button class="crm-button" id="crmAddContact">Add contact</button><button class="crm-button secondary" id="crmAddCustomerActivity">Log follow-up</button></div>
      <div class="crm-two"><details class="crm-panel" open><summary>Contacts (${d.contacts?.length||0})</summary>${list(d.contacts,y=>`<div class="crm-item"><strong>${esc(y.full_name)}</strong> ${y.is_primary?'<span class="crm-pill active">Primary</span>':''}<div>${esc(y.job_title||'')} · ${esc(y.phone||'')} · ${esc(y.email||'')}</div></div>`)}</details><details class="crm-panel" open><summary>Activities (${d.activities?.length||0})</summary>${list(d.activities,y=>`<div class="crm-item"><strong>${esc(y.subject)}</strong><div>${esc(y.activity_type)} · ${esc(y.status)} · ${date(y.scheduled_at||y.created_at)}</div><div class="crm-muted">${esc(y.outcome||y.details||'')}</div></div>`)}</details></div>
      <div class="crm-two"><details class="crm-panel"><summary>Sales (${d.sales?.length||0})</summary>${list(d.sales,y=>`<div class="crm-item">${esc(y.receipt_number)} · ${money(y.total,y.currency)} · ${esc(y.status)}</div>`)}</details><details class="crm-panel"><summary>Jobs (${d.jobs?.length||0})</summary>${list(d.jobs,y=>`<div class="crm-item">${esc(y.job_number)} · ${esc(y.title)} · ${esc(y.status)}</div>`)}</details></div>
      <div class="crm-two"><details class="crm-panel"><summary>Documents (${d.documents?.length||0})</summary>${list(d.documents,y=>`<div class="crm-item">${esc(y.document_number)} · ${esc(y.document_type)} · ${money(y.total,y.currency)} · ${esc(y.status)}</div>`)}</details><details class="crm-panel"><summary>Communication (${d.communications?.length||0})</summary>${list(d.communications,y=>`<div class="crm-item">${esc(y.channel)} · ${esc(y.subject||y.destination)} · ${esc(y.status)}</div>`)}</details></div>`;
      role();$('crmAddContact')?.addEventListener('click',()=>addContact(x));$('crmAddCustomerActivity')?.addEventListener('click',()=>{open('crmLeadsWorkspace',document.querySelector('[data-crm-view="crmLeadsWorkspace"]'));$('crmActivityCustomer').value=x.id});
    }catch(e){p.innerHTML=`<div class="crm-status error">${esc(e.message)}</div>`}
  }
  async function addContact(x){const full_name=prompt(`Contact name for ${x.name}`);if(!full_name)return;try{await rpc('save_crm_contact',{p_contact_id:null,p_customer_id:x.id,p_data:{full_name,phone:prompt('Phone')||'',email:prompt('Email')||'',preferred_channel:'whatsapp',is_primary:false}});await customer360(x)}catch(e){status('crmCustomerStatus',e.message,true)}}
  async function loadCRM(){await Promise.all([loadCustomers(),loadLeads(),loadCampaigns(),loadDashboard()])}
  async function loadLeads(){try{const {data,error}=await client().from('crm_leads').select('*').is('archived_at',null).order('updated_at',{ascending:false}).limit(1000);if(error)throw error;S.leads=data||[];renderLeads();relations();status('crmLeadStatus',`${S.leads.length} lead(s) loaded.`)}catch(e){status('crmLeadStatus',e.message,true)}}
  function renderLeads(){const q=$('crmLeadSearch').value.toLowerCase(),stage=$('crmLeadStageFilter').value,rows=S.leads.filter(x=>(!stage||x.stage===stage)&&(!q||[x.lead_code,x.name,x.company_name,x.source,...(x.tags||[])].some(v=>String(v||'').toLowerCase().includes(q)))),body=$('crmLeadRows');body.innerHTML=rows.length?'':'<tr><td colspan="6" class="crm-empty">No matching leads.</td></tr>';rows.forEach(x=>{const tr=document.createElement('tr');tr.innerHTML=`<td><strong>${esc(x.name)}</strong><div class="crm-muted">${esc(x.lead_code)} · ${esc(x.company_name||x.source)}</div></td><td><span class="crm-pill ${esc(x.stage)}">${esc(x.stage)}</span></td><td>${money(x.estimated_value,x.currency)}</td><td>${Number(x.probability||0).toFixed(0)}%</td><td>${date(x.next_followup_at)}</td><td class="crm-actions"></td>`;[['Edit','ghost',()=>editLead(x)],['Advance','secondary',()=>advance(x)],['Won','secondary',()=>moveLead(x,'won')],['Lost','danger',()=>moveLead(x,'lost')],['Activity','ghost',()=>{$('crmActivityLead').value=x.id;$('crmActivityForm').scrollIntoView({behavior:'smooth'})}]].forEach(([l,k,f])=>{const b=document.createElement('button');b.className=`crm-button ${k}`;b.textContent=l;b.onclick=f;if(!canWrite())b.style.display='none';tr.lastElementChild.appendChild(b)});body.appendChild(tr)})}
  function resetLead(){const f=$('crmLeadForm');f.reset();f.elements.id.value='';f.elements.source.value='walk_in';f.elements.stage.value='new';f.elements.currency.value='USD';f.elements.estimated_value.value='0';f.elements.probability.value='10';$('crmLeadFormTitle').textContent='Lead record';status('crmLeadFormStatus','')}
  function editLead(x){if(!canWrite())return;resetLead();const f=$('crmLeadForm');Object.entries(x).forEach(([k,v])=>{const i=f.elements[k];if(!i)return;if(i.type==='datetime-local')i.value=v?String(v).slice(0,16):'';else i.value=Array.isArray(v)?v.join(', '):(v??'')});$('crmLeadFormTitle').textContent=`Edit ${x.lead_code}`;f.scrollIntoView({behavior:'smooth'})}
  async function saveLead(e){e.preventDefault();if(!canWrite())return status('crmLeadFormStatus','Auditor access is read-only.',true);try{const raw=obj(e.currentTarget),id=raw.id||null;delete raw.id;raw.tags=tags(raw.tags);raw.estimated_value=Number(raw.estimated_value||0);raw.probability=Number(raw.probability||0);raw.campaign_id=raw.campaign_id||null;raw.next_followup_at=raw.next_followup_at?new Date(raw.next_followup_at).toISOString():null;await rpc('save_crm_lead',{p_lead_id:id,p_data:raw});resetLead();await Promise.all([loadLeads(),loadDashboard()]);status('crmLeadFormStatus',id?'Lead updated and audited.':'Lead captured and audited.')}catch(x){status('crmLeadFormStatus',x.message,true)}}
  async function advance(x){const i=STAGES.indexOf(x.stage),next=STAGES[Math.min(i+1,5)];if(next&&next!==x.stage)await moveLead(x,next)}
  async function moveLead(x,to){if(!canWrite())return;let reason=prompt(`Reason / outcome for moving ${x.lead_code} to ${to}`);if(reason===null)return;let customerId=null;if(to==='won'&&S.customers.length&&confirm('Convert to an existing customer? Select Cancel to create a customer from this lead.')){const key=prompt('Existing customer code or exact name');const c=S.customers.find(y=>y.customer_code===key||y.name.toLowerCase()===String(key||'').toLowerCase());if(!c)return alert('Customer not found.');customerId=c.id}try{await rpc('transition_crm_lead',{p_lead_id:x.id,p_stage:to,p_reason:reason.trim()||`Moved to ${to}`,p_customer_id:customerId});await Promise.all([loadLeads(),loadDashboard(),loadCustomers()])}catch(e){status('crmLeadStatus',e.message,true)}}
  async function saveActivity(e){e.preventDefault();if(!canWrite())return status('crmActivityStatus','Auditor access is read-only.',true);try{const raw=obj(e.currentTarget),customer=raw.customer_id||null,lead=raw.lead_id||null;delete raw.customer_id;delete raw.lead_id;if(!customer&&!lead)throw new Error('Select a customer or lead.');raw.scheduled_at=raw.scheduled_at?new Date(raw.scheduled_at).toISOString():null;raw.completed_at=raw.status==='completed'?new Date().toISOString():null;raw.outcome=raw.status==='completed'?raw.details:null;await rpc('log_crm_activity',{p_customer_id:customer,p_lead_id:lead,p_data:raw});e.currentTarget.reset();await loadDashboard();status('crmActivityStatus','Activity saved and audited.')}catch(x){status('crmActivityStatus',x.message,true)}}
  async function loadCampaigns(){try{const {data,error}=await client().from('crm_campaigns').select('*').order('created_at',{ascending:false}).limit(300);if(error)throw error;S.campaigns=data||[];renderCampaigns();relations()}catch(e){status('crmCampaignStatus',e.message,true)}}
  function renderCampaigns(){$('crmCampaignList').innerHTML=S.campaigns.length?S.campaigns.map(x=>`<div class="crm-item"><strong>${esc(x.name)}</strong> <span class="crm-pill ${esc(x.status)}">${esc(x.status)}</span><div>${esc(x.channel)} · ${money(x.budget,x.currency)} · ${esc(x.starts_on||'No start date')}</div></div>`).join(''):'<div class="crm-empty">No campaigns recorded.</div>'}
  async function saveCampaign(e){e.preventDefault();if(!canWrite())return status('crmCampaignStatus','Auditor access is read-only.',true);try{const raw=obj(e.currentTarget);raw.branch_id=ctx().profile.branch_id;raw.campaign_code=`CMP-${new Date().toISOString().slice(0,7).replace('-','')}-${Date.now().toString().slice(-6)}`;raw.budget=Number(raw.budget||0);raw.status='planned';raw.starts_on=raw.starts_on||null;raw.ends_on=raw.ends_on||null;const {error}=await client().from('crm_campaigns').insert(raw);if(error)throw error;e.currentTarget.reset();await loadCampaigns();status('crmCampaignStatus','Campaign created and audited.')}catch(x){status('crmCampaignStatus',x.message,true)}}
  function relations(){if(!$('crmActivityCustomer'))return;$('crmActivityCustomer').innerHTML='<option value="">None</option>'+S.customers.filter(x=>!x.archived_at).map(x=>`<option value="${x.id}">${esc(x.customer_code||'')} ${esc(x.name)}</option>`).join('');$('crmActivityLead').innerHTML='<option value="">None</option>'+S.leads.filter(x=>!['won','lost'].includes(x.stage)).map(x=>`<option value="${x.id}">${esc(x.lead_code)} ${esc(x.name)}</option>`).join('');$('crmLeadCampaign').innerHTML='<option value="">No campaign</option>'+S.campaigns.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}
  async function loadDashboard(){try{const d=await rpc('get_crm_dashboard',{p_from:$('crmDashFrom').value,p_to:$('crmDashTo').value});S.dashboard=d;const s=d.leads||d.summary||{};$('crmOpenLeads').textContent=s.open??s.open_leads??S.leads.filter(x=>!['won','lost'].includes(x.stage)).length;$('crmWonLeads').textContent=s.won??S.leads.filter(x=>x.stage==='won').length;$('crmConversionRate').textContent=`${Number(s.conversion_rate||0).toFixed(1)}%`;$('crmWeightedValue').textContent=Object.entries(s.weighted_value||{}).map(([c,v])=>money(v,c)).join(' · ')||'USD 0.00';bars('crmFunnel',d.funnel||[],'stage','lead_count');bars('crmSources',d.sources||[],'source','total');$('crmUpcomingActivities').innerHTML=(d.upcoming||[]).length?d.upcoming.map(x=>`<div class="crm-item"><strong>${esc(x.subject)}</strong><div>${esc(x.activity_type)} · ${esc(x.customer||x.lead||'Internal')} · ${date(x.scheduled_at)}</div>${canWrite()?`<button class="crm-button ghost" data-complete="${x.id}">Complete</button>`:''}</div>`).join(''):'<div class="crm-empty">No upcoming activities.</div>';document.querySelectorAll('[data-complete]').forEach(b=>b.onclick=()=>completeActivity(b.dataset.complete))}catch(e){status('crmLeadStatus',e.message,true)}}
  function bars(id,rows,k,v){const max=Math.max(1,...rows.map(x=>Number(x[v]||0)));$(id).innerHTML=rows.length?rows.map(x=>`<div class="crm-bar"><span>${esc(x[k])}</span><span class="crm-track"><span class="crm-fill" style="width:${Math.max(3,Number(x[v]||0)/max*100)}%"></span></span><strong>${Number(x[v]||0)}</strong></div>`).join(''):'<div class="crm-empty">No data for this period.</div>'}
  async function completeActivity(id){try{await rpc('complete_crm_activity',{p_activity_id:id,p_outcome:prompt('Completion outcome')||'Completed'});await loadDashboard()}catch(e){status('crmActivityStatus',e.message,true)}}
  async function loadCash(){if(!$('crmCashFrom')?.value)return;try{status('crmCashStatus','Calculating from recorded financial transactions…');const d=await rpc('get_cash_conversion_cycle',{p_from:$('crmCashFrom').value,p_to:$('crmCashTo').value,p_currency:$('crmCashCurrency').value||null});S.cash=d;renderCash(d);status('crmCashStatus','Cash conversion and operating-cash analysis loaded.')}catch(e){status('crmCashStatus',e.message,true)}}
  function renderCash(d){$('crmCashMethod').textContent=d.methodology||'Standard CCC = inventory days + receivable days − payable days.';$('crmCashCards').innerHTML=(d.currencies||[]).map(x=>`<div class="crm-card"><span class="label">${esc(x.currency)} CCC</span><strong>${Number(x.cash_conversion_cycle_days||0).toFixed(2)} days</strong><div>Inventory ${Number(x.inventory_days||0).toFixed(2)} · Receivables ${Number(x.receivable_days||0).toFixed(2)} · Payables ${Number(x.payable_days||0).toFixed(2)}</div></div><div class="crm-card"><span class="label">${esc(x.currency)} operating outflows</span><strong>${money(x.total_operating_outflows,x.currency)}</strong><div>Expenses ${money(x.operating_expenses,x.currency)} · Paid purchases ${money(x.paid_purchases,x.currency)}</div></div><div class="crm-card"><span class="label">${esc(x.currency)} net operating cash flow</span><strong>${money(x.net_operating_cash_flow,x.currency)}</strong><div>Inflows ${money(x.cash_inflows,x.currency)}</div></div><div class="crm-card"><span class="label">${esc(x.currency)} funding required</span><strong>${money(x.working_capital_funding_required,x.currency)}</strong><div>Daily outflow ${money(x.average_daily_operating_outflow,x.currency)}</div><div class="crm-muted">${x.data_quality?.complete?'Data complete':'Review data-quality warnings'}</div></div>`).join('');$('crmExpenseBreakdown').innerHTML=(d.expense_breakdown||[]).map(x=>`<tr><td>${esc(x.currency)}</td><td>${esc(x.category)}</td><td>${money(x.amount,x.currency)}</td><td>${x.entries}</td></tr>`).join('')||'<tr><td colspan="4" class="crm-empty">No expenses.</td></tr>';$('crmPurchaseBreakdown').innerHTML=(d.purchase_breakdown||[]).map(x=>`<tr><td>${esc(x.document_number)}</td><td>${esc(x.document_type)}</td><td>${esc(x.status)}</td><td>${money(x.total,x.currency)}</td><td>${money(x.paid_total,x.currency)}</td><td>${esc(x.issue_date)}</td></tr>`).join('')||'<tr><td colspan="6" class="crm-empty">No purchasing documents.</td></tr>'}
  function exportCash(){if(!S.cash)return status('crmCashStatus','Run the analysis first.',true);const rows=[];S.cash.currencies?.forEach(x=>rows.push(['Cash cycle',x.currency,'CCC days',x.cash_conversion_cycle_days,'Inventory days',x.inventory_days,'Receivable days',x.receivable_days,'Payable days',x.payable_days,'Outflows',x.total_operating_outflows,'Funding',x.working_capital_funding_required]));S.cash.expense_breakdown?.forEach(x=>rows.push(['Expense',x.currency,x.category,x.amount,'Entries',x.entries]));S.cash.purchase_breakdown?.forEach(x=>rows.push(['Purchase',x.currency,x.document_number,x.document_type,x.status,x.total,x.paid_total,x.issue_date]));csv(`OmniHub-Cash-Cycle-${$('crmCashFrom').value}-to-${$('crmCashTo').value}.csv`,['Record','Currency','Field 1','Value 1','Field 2','Value 2','Field 3','Value 3','Field 4','Value 4','Field 5','Value 5','Field 6','Value 6'],rows)}
  function realtime(){try{S.channel=client().channel('omnihub-crm-v1').on('postgres_changes',{event:'*',schema:'public',table:'customers'},loadCustomers).on('postgres_changes',{event:'*',schema:'public',table:'crm_leads'},()=>Promise.all([loadLeads(),loadDashboard()])).on('postgres_changes',{event:'*',schema:'public',table:'crm_activities'},loadDashboard).on('postgres_changes',{event:'*',schema:'public',table:'crm_customer_contacts'},()=>S.customer&&customer360(S.customer)).on('postgres_changes',{event:'*',schema:'public',table:'crm_campaigns'},loadCampaigns).subscribe()}catch(_e){}}
  let attempts=0;const timer=setInterval(()=>{attempts++;try{const c=ctx();if(!c?.db||!c?.profile){if(attempts>120)clearInterval(timer);return}clearInterval(timer);mount();realtime();if(location.hash==='#crm')open('crmCustomersWorkspace',document.querySelector('[data-crm-view="crmCustomersWorkspace"]'));if(location.hash==='#leads')open('crmLeadsWorkspace',document.querySelector('[data-crm-view="crmLeadsWorkspace"]'));if(location.hash==='#cash-cycle')open('crmCashWorkspace',document.querySelector('[data-crm-view="crmCashWorkspace"]'))}catch(e){clearInterval(timer);console.error('OmniHub CRM failed to initialise',e)}},250);
})();
